FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

SHELL ["powershell","-command"]

RUN Set-TimeZone 'Central Standard Time'

CMD hostname; (get-timezone).DisplayName; (get-date).ToShortTimeString();







# NOTE:  this is broken intentionally for a demo of base images