# syntax=docker/dockerfile:1.3-labs

FROM ubuntu


RUN <<SCRIPT

apt-get update

apt-get install -y bat jq

rm -rf /var/lib/apt/lists/*

SCRIPT


ENTRYPOINT ["jq", "-C"]







### build
# docker build -t jq:h -f Dockerfile.heredoc .

### links
#
# heredocs post:
#   https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/
#
# dockerfile syntax docs:
#   https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md 
#